[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "asyncio: marks tests as asyncio",
    "integration: marks tests as integration tests",
    "slow: marks tests as slow running"
]
addopts = "-v --tb=short --strict-markers"
